{
  id: 2392,
  parent_id: 0,
  status: 'processing',
  order_key: 'wc_order_nvpNcl5E04ajR',
  number: '2392',
  currency: 'EUR',
  version: '5.1.0',
  prices_include_tax: false,
  date_created: '2021-05-01T15:40:47',
  date_modified: '2021-05-01T15:42:47',
  customer_id: 4,
  discount_total: '0.00',
  discount_tax: '0.00',
  shipping_total: '10.00',
  shipping_tax: '0.00',
  cart_tax: '0.00',
  total: '96.00',
  total_tax: '0.00',
  billing: {
    first_name: 'test',
    last_name: 'test',
    company: '',
    address_1: 'via orsiera 18',
    address_2: '',
    city: 'tornino',
    state: 'PD',
    postcode: '10141',
    country: 'IT',
    email: 'yuanfeng8791@sina.com',
    phone: '3888787897'
  },
  shipping: {
    first_name: 'test',
    last_name: 'test',
    company: '',
    address_1: 'via orsiera 18',
    address_2: '',
    city: 'tornino',
    state: 'PD',
    postcode: '10141',
    country: 'IT'
  },
  payment_method: 'bacs',
  payment_method_title: 'Bonifico bancario',
  transaction_id: '',
  customer_ip_address: '82.54.134.44',
  customer_user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36',
  created_via: 'checkout',
  customer_note: '',
  date_completed: null,
  date_paid: '2021-05-01T17:42:47',
  cart_hash: 'df76c947ee2f983653fb96b7529a9027',
  line_items: [
    {
      id: 3,
      name: 'Printed Green Tshirt',
      sku: '',
      product_id: 168,
      variation_id: 0,
      quantity: 2,
      tax_class: '',
      price: '28.00',
      subtotal: '56.00',
      subtotal_tax: '0.00',
      total: '56.00',
      total_tax: '0.00',
      taxes: [],
      meta: []
    },
    {
      id: 4,
      name: 'Abiti-1',
      sku: '',
      product_id: 240,
      variation_id: 0,
      quantity: 2,
      tax_class: '',
      price: '15.00',
      subtotal: '30.00',
      subtotal_tax: '0.00',
      total: '30.00',
      total_tax: '0.00',
      taxes: [],
      meta: []
    }
  ],
  tax_lines: [],
  shipping_lines: [
    {
      id: 5,
      method_title: 'Flat rate',
      method_id: 'flat_rate',
      total: '10.00',
      total_tax: '0.00',
      taxes: []
    }
  ],
  fee_lines: [],
  coupon_lines: [],
  refunds: [],
  _links: {
    self: [ [Object] ],
    collection: [ [Object] ],
    customer: [ [Object] ]
  }
}

